### ISSUE TITLE
月份切换问题（已解决）

### ISSUE THREAD

**Issue by yi279095547** [wuda615/StickyCalendar#7]
当日期是当天的30号的时候2月没有了，显示为3月，当日期是31号的时候，左右滑动所有天数低于31天的月份没有了，总结的问题就是，左右滑动不会出现天数比当前日期小的月份

**Comment by mutouzhang** [comment]
他用的calender来构造数据，不应该出现上面的情况才对，关注

**Comment by yi279095547** [comment]
你可以自己去改手机时间去尝试，以前没发现，正好这两天是30号和31号才发现的，我正在找原因

**Comment by yi279095547** [comment]
问题已经解决，SpecialCalendar#getRealYearMonth方法有问题， calendar.set(Calendar.MONTH, month + jumpMonth); set方法是单纯设定日期，当日期为31号的时候设置其他没有31号的月份的时候，日期就会跳一个月，这里有两种解决方法，第一：在set month之前calendar.set(Calendar.DATE,1);，或者改这句为calendar.add(Calendar.MONTH,jumpMonth); 但是这样会导致在SpecialCalendar#getDateByYearMonth方法中获取总天数的时候总是31，在set month之前加入cal.set(Calendar.DATE,1);就ok了

**Comment by wuda615** [comment]
@yi279095547 thank you
